<a href="https://colab.research.google.com/github/HolmesZ/Pytorch-Tutorial-Codymy/blob/main/02_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
- A torch tensor is a multi-dimensional matrix containing elements of a single data type.
- Similar to numpy arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
- Default data type of float32
- More suitable for deep learning than a numpy array.

In [ ]:
import torch
import numpy as np

# Lists

In [ ]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# Numpy arrays

In [ ]:
np1 = np.random.rand(3, 4)
np1

array([[0.65971028, 0.60284403, 0.07358667, 0.24567602],
       [0.31648684, 0.15340012, 0.5467066 , 0.82822594],
       [0.68236829, 0.53816204, 0.09354799, 0.45857602]])

In [ ]:
np1.dtype

dtype('float64')

# Tensors

In [ ]:
tensor_2d = torch.randn(3, 4)
tensor_2d
# tensor_2d.dtype

tensor([[-0.6279,  0.0653, -0.4436, -0.9885],
        [ 0.7763, -0.6555, -0.7557,  1.0194],
        [-0.2625, -1.3388, -1.5519,  1.6585]])

In [ ]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6597, 0.6028, 0.0736, 0.2457],
        [0.3165, 0.1534, 0.5467, 0.8282],
        [0.6824, 0.5382, 0.0935, 0.4586]], dtype=torch.float64)