<a href="https://colab.research.google.com/github/HolmesZ/Pytorch-Tutorial-Codymy/blob/main/03_tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and View
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape if we dont't know the number of items using -1
my_torch = my_torch.reshape(-1, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = my_torch.view(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Differences between shape and view
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [ ]:
# with reshape and view, they will update
t = torch.arange(10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
t1 = t.reshape(2, -1)
t1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
t[4] = 20
t1

tensor([[ 0,  1,  2,  3, 20],
        [ 5,  6,  7,  8,  9]])

In [ ]:
# Slices
t2 = torch.arange(10)
t2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Grab a specific item
t2[7]

tensor(7)

In [ ]:
t2 = t2.reshape(5, 2)
t2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
t2[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [ ]:
t2.is_contiguous()

True