<a href="https://colab.research.google.com/github/HolmesZ/Pytorch-Tutorial-Codymy/blob/main/04_Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Math Operations
- Add, Subtract, Multiply, Reminders, Exponents
- Shorthand and Longhand
- Ressignment

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [ ]:
# Shorthand
print(tensor_a + tensor_b)
print(tensor_b - tensor_a)
print(tensor_a * tensor_b)
print(tensor_b / tensor_a)
print(tensor_b % tensor_a)
print(tensor_a ** tensor_b)

tensor([ 6,  8, 10, 12])
tensor([4, 4, 4, 4])
tensor([ 5, 12, 21, 32])
tensor([5.0000, 3.0000, 2.3333, 2.0000])
tensor([0, 0, 1, 0])
tensor([    1,    64,  2187, 65536])


In [ ]:
# torch Longhand
print(torch.add(tensor_a, tensor_b))
print(torch.sub(tensor_b, tensor_a))
print(torch.mul(tensor_a, tensor_b))
print(torch.div(tensor_b, tensor_a))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 6,  8, 10, 12])
tensor([4, 4, 4, 4])
tensor([ 5, 12, 21, 32])
tensor([5.0000, 3.0000, 2.3333, 2.0000])
tensor([0, 0, 1, 0])
tensor([    1,    64,  2187, 65536])


In [ ]:
# Longhand
tensor_a.add(tensor_b)
# Reassinment by add_
# tensor_a += tensor_b
tensor_a.add_(tensor_b)
print("tensor_a was reassinment: ", tensor_a)

tensor_a was reassinment:  tensor([ 6,  8, 10, 12])
